# Generated by Django 4.0.4 on 2022-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_proyect_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={},
        ),
        migrations.AlterField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
